apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: db
  name: db
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: db
  template:
    metadata:
      labels:
        app: db
    spec:
      containers:
      - image: {{ .Values.dbImageName }}
        name: postgres
        env:
        - name: POSTGRES_USER
          value: postgres
        - name: POSTGRES_PASSWORD
          valueFrom:
            secretKeyRef:
              name: db-secret
              key: POSTGRES_PASSWORD
        ports:
        - containerPort: {{ .Values.dbContainerPort }}
          name: postgres
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: db-pvc-data
      volumes:
      - name: db-pvc-data
        persistentVolumeClaim:
          claimName: vote-app-db-pvc