apiVersion: v1
kind: Service
metadata:
  labels:
    app: db
  name: db
spec:
  type: {{ .Values.dbSvcType }}
  ports:
  - name: "db-service"
    port: {{ .Values.dbSvcPort }}
    targetPort: {{ .Values.dbSvcTargetPort }}
  selector:
    app: db
  