apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: vote-app-db-pvc
spec:
  accessModes:
    - ReadWriteOnce
  volumeMode: Filesystem
  resources:
    requests:
      storage: 1Gi
  storageClassName: {{ .Values.storageClassName }}
