apiVersion: v1
kind: Service
metadata:
  labels:
    app: redis
  name: redis
spec:
  type: {{ .Values.redisSvcType }}
  ports:
  - name: "redis-service"
    port: {{ .Values.redisSvcPort }}
    targetPort: {{ .Values.redisSvcTargetPort }}
  selector:
    app: redis
  