apiVersion: v1
kind: Service
metadata:
  labels:
    app: result
  name: result
spec:
  type: {{ .Values.resultSvcType }}
  ports:
  - name: "result-service"
    port: {{ .Values.resultSvcPort }}
    targetPort: {{ .Values.resultSvcTargetPort }}
  selector:
    app: result