apiVersion: v1
kind: Service
metadata:
  labels:
    app: vote
  name: vote
spec:
  type: {{ .Values.voteSvcType }}
  ports:
  - name: "vote-service"
    port: {{ .Values.voteSvcPort }}
    targetPort: {{ .Values.voteSvcTargetPort }}
  selector:
    app: vote