apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: vote
  name: vote
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: vote
  template:
    metadata:
      labels:
        app: vote
    spec:
      containers:
      - image: {{ .Values.voteImageName }}
        name: vote
        ports:
        - containerPort: {{ .Values.voteContainerPort }}
          name: vote